### ISSUE TITLE
macOSクライアントの挙動について

### ISSUE THREAD

**Issue by khisanag** [search-future/miyou.tv#10]
当方、mac OS 10.15で、Chinachu(Gamma)との組み合わせで使用していますが、v0.11.7では、番組表から番組を選択し、「再生」をクリックして、プレーヤーが立ち上がって番組が再生されるという挙動で何の問題もないのですが、それ以降のバージョンでは、アプリのセキュリティー強化の影響か、

{
 “EC”: 401,
 “Edesc”: “Auth error”
}

というポップアップが出て、またプレーヤーの中も「Couldn’t load pulg in.」とメッセージが出て、思うような挙動になりません。番組表示自体は表示されます。

何か設定漏れとかあれば、ご教示いただければ幸いです。

**Comment by takaakis62** [comment]
コメントAPIの認証に失敗したときのエラーです。モリタポアカウントの設定が間違っているかAPI自体の不調です。
「Couldn’t load pulg in.」は動画再生プラグインが読み込めない時に出ます。
手元のmacOS 10.15.4では再現しませんでした。

**Comment by khisanag** [comment]
ご回答ありがとうございました。
モリタポアカウントを入れ(コメント不要なので入れていませんでした)、Homebrewとmpvのインストールを再度やり直したところ、期待通りの挙動となりました。
今後の開発にも期待しています。

**Comment by takaakis62** [comment]
libvlcを廃止した影響かもしれないですね。
解決したようで良かったです。

**Comment by takaakis62** [comment]
同梱ライブラリの不足が原因でした。
v1.3.4で修正しました。

**Comment by khisanag** [comment]
ご対応ありがとうございました。
