### ISSUE TITLE
Androidのデュアルモノラルについて

### ISSUE THREAD

**Issue by unicode45** [search-future/miyou.tv#11]
Android版の場合、デュアルモノラルの音声選択機能がないため、
ニュース番組を視聴する場合は仕方なくWindowsで使っていますが、
Android環境でもデュアルモノラルの音声を選択する方法はありませんでしょうか？

**Comment by takaakis62** [comment]
現状Android版でのデュアルモノラル対応は難しいです

**Comment by takaakis62** [comment]
v1.4.0からステレオモードで左右どちらかの音声だけを再生できるようになりました。
