### ISSUE TITLE
Android版のRequest failed with status code 401について

### ISSUE THREAD

**Issue by unicode45** [search-future/miyou.tv#12]
Windows版では同じ設定で問題なく使えていますが、
Android版（1.2~1.3xまで試してみました）では
同じ設定で試しても

Request failed with status code 401

{
"EC":401
"Edesc":"Auth error."
}
のエラーが発生します。
サーバーはChinachuでログイン認証を使用しています。

**Comment by takaakis62** [comment]
モリタポアカウントでのコメントAPIの認証に失敗しているように見えます。
コメント以外の機能は正常に動作しますか？

**Comment by unicode45** [comment]
空欄にしていたモリタポアカウント情報を記入して
{
"EC":401
"Edesc":"Auth error."
}
エラーは表示されなくなりましたが、「Request failed with status code 401」は消えず、Chinachu自体にログインできない状況が続いています。

**Comment by takaakis62** [comment]
Androidでは同じように認証できないようです。
実装を見直します。

**Comment by takaakis62** [comment]
v1.3.6で修正しました。
Google Playでも公開済みです。
