### ISSUE TITLE
一部局にスレッドが表示されない

### ISSUE THREAD

**Issue by KawakawaRitsuki** [search-future/miyou.tv#2]
田舎に住んでる者です。
MiyouTV、とても素晴らしいのですが現在NHK以外のチャンネルで利用することが出来ません（スレッドが表示されません）。

NHKのみという事象から推測するにチャンネル名から取得できていない感じですかね？
もしそうであれば地方局名と広域ネットの局名の関連付け機能を付けていただけるとうれしいです。（違ったらゴメンナサイ）

最低限、スレッドを検索して選択する機能を付けていただけると幸いです。

**Comment by takaakis62** [comment]
ご意見ありがとうございます。
ネット局を指定する機能を検討しています。
検討の上、できるだけ早い実装を目指します。

**Comment by KawakawaRitsuki** [comment]
お返事ありがとうございます。
楽しみにしています！

**Comment by takaakis62** [comment]
v0.6.0で対応しました。
よろしくお願いします。

**Comment by KawakawaRitsuki** [comment]
対応、確認しました！
迅速な対応ありがとうございました！
