### ISSUE TITLE
miyoutv-agentの生成するファイルの名前

### ISSUE THREAD

**Issue by aoshimak** [search-future/miyou.tv#3]
現在miyoutvのインストールに挑戦中です。
現在miyoutv−agent0.5.2の導入だけ終わったところです。
mirakurunと組み合わせて、１時間ごとの録画が繰り返され、ファイルが生成されています。
それらのファイル名が全て、[日付][時間]MiyouTV Record_n.tsになります。

番組名部分は、取得できればその番組名、ダメならMiyouTV Recordになるようなコードになってるように見受けられますが、この状況は番組名が取得できていない、と理解して良いでしょうか？
その場合、mirakurunとのデータのやり取りの設定がまずいのでしょうか？
できればファイル名に番組名ぐらいは反映させたいのですが、どの辺をチェックすれば良いでしょう？

また、miyoutvのlinux版は３種類あるようですが、どれを導入するべきでしょうか？
導入にはソースを使う、nwと言うのを使う、electronというのを使う、それぞれの違いはどこにあるのでしょうか？個人的な希望はchinachuのようにweb i/f を介して見に行けるようなものがあればと思っています。

また一度だけnwと付いたものを展開してinstall.shを実行しましたが、コンパイルオプションのc++11というのに関するエラーが出ました。使用している環境がチューナーボードの関係でCentos6.8なもので、c++のバージョンを上げるよりはそこの指定をc++0xに変えてcmakeを通したいです。makefile的なものはどの辺をいじったら良いでしょう？

環境はCentos6.8（非XWindow環境）/PX-Q3PE/ChinachuBeta/Mirakurun/rivarunです。

**Comment by takaakis62** [comment]
> 番組名部分は、取得できればその番組名、ダメならMiyouTV Recordになるようなコードになってるように見受けられますが、この状況は番組名が取得できていない、と理解して良いでしょうか？
> その場合、mirakurunとのデータのやり取りの設定がまずいのでしょうか？
> できればファイル名に番組名ぐらいは反映させたいのですが、どの辺をチェックすれば良いでしょう？

Chinachu betaとmiyoutv-agentを使用した全録では番組がファイル名に反映されない仕様です。
クライアントのmiyoutvを使用することで番組情報と紐づけされます。

> また、miyoutvのlinux版は３種類あるようですが、どれを導入するべきでしょうか？
> 導入にはソースを使う、nwと言うのを使う、electronというのを使う、それぞれの違いはどこにあるのでしょうか？個人的な希望はchinachuのようにweb i/f を介して見に行けるようなものがあればと思っています。

v0.4以前と互換性のあるNW.js版と今後ベースとなるElectron版の2種類です。
新しくインストールする場合はElectron版を推奨します。
それぞれベースのフレームワークが違います。

> また一度だけnwと付いたものを展開してinstall.shを実行しましたが、コンパイルオプションのc++11というのに関するエラーが出ました。使用している環境がチューナーボードの関係でCentos6.8なもので、c++のバージョンを上げるよりはそこの指定をc++0xに変えてcmakeを通したいです。makefile的なものはどの辺をいじったら良いでしょう？

おそらくその方法ではインストールできませんので、こちらでインストールした手順を示します。
ただし、動作を確認できませんでした。今後の対応は未定です。
```
$ su -
# yum install -y gcc-c++ make cmake
# curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
# sudo yum install -y nodejs
# sudo yum install -y centos-release-scl
# sudo yum install -y devtoolset-4-gcc-c++
# rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
# rpm -Uvh http://li.nux.ro/download/nux/dextop/el6/x86_64/nux-dextop-release-0-2.el6.nux.noarch.rpm
# yum install vlc-devel
# exit
$ wget https://github.com/search-future/miyou.tv/releases/download/v0.5.2/miyoutv-electron-linux-x64.tar.gz
$ cd miyoutv-linux-x64/
$ scl enable devtoolset-4 ./install.sh
```
クライアントのmiyoutvは実際に視聴する環境で導入してください。
Chinachuとmiyoutv-agentを導入しているPCとは別のPCにmiyoutvを導入しても使用できます。

**Comment by takaakis62** [comment]
録画したファイルに番組情報が反映されない仕様です。
番組ごとに録画したい場合はChinachu gammaを使用して予約ルールを設定してください。この場合、miyoutv-agentの導入は不要です。
また、ElectronとNW.jsに対応しないため、クライアントではCentOS6をサポートしません。

**Comment by aoshimak** [comment]
ありがとございました。録画がHDD全量を埋め、順次古い方から削られていくのを確認しました。普段使わないWindowsノートにElectron-ia32版を入れ、番組表形式で見る事ができるのを確認しました。便利に使わせていただきます。
